apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: emby-backend
  template:
    metadata:
      anotations:
        {{ if .Values.backend.instrumentation.enabled }}
        instrumentation.opentelemetry.io/inject-{{ .Values.backend.instrumentation.language }}: "{{ .Values.backend.instrumentation.namespace }}/{{ .Values.backend.instrumentation.name }}"
        {{- end }}
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: emby-backend
    spec:
      containers:
      - name: emby-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- if .Values.backend.persistence.enabled }}
        volumeMounts:
        - name: backend-storage
          mountPath: {{ .Values.backend.persistence.mountPath }}
        {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: emby-backend-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: emby-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    app: emby-backend
