apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: emby-frontend
  template:
    metadata:
      anotations:
        {{ if .Values.frontend.instrumentation.enabled }}
        instrumentation.opentelemetry.io/inject-{{ .Values.frontend.instrumentation.language }}: "{{ .Values.frontend.instrumentation.namespace }}/{{ .Values.frontend.instrumentation.name }}"
        {{- end }}
        {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: emby-frontend
    spec:
      containers:
      - name: emby-frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: 5173
        env:
        {{- range $key, $value := .Values.frontend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: emby-frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: emby-frontend
